@extends('superAdmin.layouts.main')

@push('title')
  Reports
@endpush


@section('report-section')

<!-- Main Content -->
<div class="container-fluid">
    <div class="row">

        @include('superAdmin.layouts.sidebar')

        <!-- Content -->
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

            <!-- Alert Messages Here-->
            @if (Session('success'))
                <div class="alert alert-success" id="popup">
                    {{ session('success') }}
                </div>
                @endif

            @if (Session('error'))
                <div class="alert alert-danger" id="popup">
                        {{ session('error') }}
                </div>
            @endif
            <!-- Alert Messages Here-->

            <!-- Reports Section -->
            <div class="container-fluid">
                <h2 class="mt-4">Reports</h2>
                <div class="row mt-4">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Available Reports</h5>
                                <!-- List of Reports with Dummy Details -->
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <h6>Course Performance Report</h6>
                                        <p>Provides detailed analysis of student performance in each course. Highlights top-performing and struggling courses.</p>
                                        <p><strong>Generated on:</strong> January 15, 2023</p>
                                        <p><strong>Generated by:</strong> Admin</p>
                                        <button class="btn btn-primary" data-toggle="modal" data-target="#generateModal0">Generate</button>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

@endsection
