@extends('superAdmin.layouts.main')

@section('report-section')

<!-- Main Content -->
<div class="container-fluid">
    <div class="row">

        @include('superAdmin.layouts.sidebar')

         <!-- Content -->
      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
        <!-- Reports Section -->
       <!-- Reports Section -->
<div class="container-fluid">
    <h2 class="mt-4">Reports</h2>
    <div class="row mt-4">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Available Reports</h5>
            <!-- List of Reports with Dummy Details -->
            <ul class="list-group">
              <li class="list-group-item">
                <h6>Course Performance Report</h6>
                <p>Provides detailed analysis of student performance in each course. Highlights top-performing and struggling courses.</p>
                <p><strong>Generated on:</strong> January 15, 2023</p>
                <p><strong>Generated by:</strong> Admin</p>
              </li>
              <li class="list-group-item">
                <h6>Attendance Report</h6>
                <p>Tracks attendance data for each student. Identifies trends and patterns in attendance for better management.</p>
                <p><strong>Generated on:</strong> January 18, 2023</p>
                <p><strong>Generated by:</strong> Admin</p>
              </li>
              <li class="list-group-item">
                <h6>Student Progress Report</h6>
                <p>Evaluates the progress of each student in their respective courses. Includes overall performance and areas of improvement.</p>
                <p><strong>Generated on:</strong> January 20, 2023</p>
                <p><strong>Generated by:</strong> Admin</p>
              </li>
              <li class="list-group-item">
                <h6>Teacher Feedback Report</h6>
                <p>Summarizes feedback provided by students on teacher performance. Helps identify areas for professional development.</p>
                <p><strong>Generated on:</strong> January 22, 2023</p>
                <p><strong>Generated by:</strong> Admin</p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  
      </main>
    </div>
</div>

@endsection
